token:
  expiration_time: 86400000
  secret: my_token_dev_#4

gateway:
  ip: 192.168.0.2

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/testdb
    # url: jdbc:h2:mem:testdb
    username: sa
    # password: "{cipher}ef756d7b4d2af5866748849daf1c69e18af2bf25d4e1c8d26e2ad4c40ca7c2ce"
    password:
