token:
  expiration_time: 86400000
  secret: my_token_dev_#4

gateway:
  ip: 192.168.0.2

spring:
  datasource:
    driver-class-name: org.h2.Driver
    # url: jdbc:h2:tcp://localhost/~/testdb
    url: jdbc:h2:tcp://localhost/~/testdb3
    username: sa
    password: "{cipher}AQAZ1Zq5jrXl9VgIFRyAY2NFNZ3gGe7tdxQ1V+M0lxHJ1D605LUV5uUuMwa8kxWs0V+QUyopLCqzBw5K9TXZcp9+B6BLlwOIYPd7cUtyw7E6hcKIB9mENfwySGYzn8AsYxj0PoS0spXHjvhPD4mWjK5ATtCR22rpYOjxIBp62FyFvaVzmISTf3JwFFjmq5/POc3I/2s1NAhxfeiTeCRQt3Z8qQqsDyAZjvD1DQqea/7PbB4Bolx7yzP/0mWD5eSkHB/ayxswaMuQpcN+KvcOKEIJGEnncUO9X2LkIdi0+cwLkYbnJr3LNdXQi0SmcSOI7aOwci+4naOOq+gypb/UvXCcpqSQQ61BqgPJfpFds70ee/TtaL4y0El1B+DM4S6kmbQ="
