spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    # url: jdbc:h2:tcp://localhost/~/testdb
#    url: jdbc:h2:tcp://localhost/~/testdb3
    url: jdbc:mariadb://mariadb:3306/mydb
    username: root
    password: test1357

#order_service:
#  url: http://127.0.0.1:8000/order-service/%s/orders

order_service:
  url: http://ORDER-SERVICE/order-service/%s/orders
  exception:
    orders_is_empty: There is no item